# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# configured weekly to start with, to catch up on updates. Change to monthly eventually.
version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[dependabot:bundler] '
    groups:
      regular-updates: # Group everything except major version updates and security vulnerabilities
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[dependabot:actions] '
    groups:
      regular-updates: # Group everything except major version updates and security vulnerabilities
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: '[dependabot:docker] '
    groups:
      regular-updates: # Group everything except major version updates and security vulnerabilities
        update-types:
          - "minor"
          - "patch"
