name: Lint and test
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format github

      - name: "Haml lint"
        run: bundle exec haml-lint app/**/*.html.haml

  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Precompile assets"
        run: bundle exec rails assets:precompile

      - name: "Rspec"
        run: bundle exec rspec

  audit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Bundle audit"
        run: bundle exec bundle-audit

      - name: "Brakeman audit"
        run: bundle exec brakeman

      - name: "License audit"
        run: bundle exec license_finder