name: Lint and test
on:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Ruby lint"
        run: bundle exec rubocop --format progress --format github

      - name: "Haml lint"
        run: bundle exec haml-lint app/**/*.html.haml

  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      app-dir: .
    needs: lint
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5434 on service container to the host
          - 5434:5434
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Precompile assets"
        run: bundle exec rails assets:precompile

      - name: "Install PostgreSQL"
        run: sudo apt-get -yqq install libpq-dev

      - name: "Setup Database"
        working-directory: ${{env.app-dir}}
        env:
          POSTGRES_HOST: localhost
          RAILS_ENV: test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: bin/rails db:create db:schema:load

      - name: "Test with rspec"
        working-directory: ${{env.app-dir}}
        env:
          POSTGRES_HOST: localhost
          RAILS_ENV: test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: bundle exec rspec

  audit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Bundle audit"
        run: bundle exec bundle-audit

      - name: "Brakeman audit"
        run: bundle exec brakeman

      - name: "License audit"
        run: bundle exec license_finder